In [4]:
import numpy as np
import pandas as pd

In [5]:
df =pd.DataFrame(pd.read_csv('/workspaces/ml-zoomcamp-homework/car_fuel_efficiency.csv'))
print(len(df))
print(df)

9704
      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-whe

In [11]:
# types_of_gas = df['fuel_type']
# print(types_of_gas.nunique())

asian_cars = df[df['origin'] == "Asia"]
print(asian_cars)
print(asian_cars['fuel_efficiency_mpg'].max())

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front

In [8]:
missing_counts = df.isnull().sum()

# 2. Filter for columns with missing values (count > 0)
columns_with_missing = missing_counts[missing_counts > 0]

# 3. Count the number of such columns
num_columns_with_missing = len(columns_with_missing)

print(num_columns_with_missing)

4


In [6]:

print(df['horsepower'].median())
category_counts = df['horsepower'].value_counts().index[0]
print(category_counts)
df['horsepower'].fillna(152.0, inplace=True)
print(df['horsepower'].median())


149.0
152.0
152.0


/tmp/ipykernel_2221/1426561984.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(152.0, inplace=True)


In [19]:
import numpy as np

# --- Your custom multiplication functions (fixed small bug) ---
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

def matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result

# --- Your pipeline ---
asian_cars = df[df['origin'] == "Asia"][['vehicle_weight', 'model_year']]
X = asian_cars.head(7).to_numpy()

XT = X.T

# 1. Compute XTX = XT @ X (NOT X @ XT)
XTX = matrix_multiplication(XT, X)

# 2. Invert XTX (use numpy for this part, unless you want to implement your own Gaussian elimination)
XTX_inv = np.linalg.inv(XTX)

# 3. Create y as a column vector
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200]).reshape(-1, 1)

# 4. Compute w = XTX_inv @ XT @ y using your functions
# First: XT @ y
XTy = matrix_multiplication(XT, y)

# Then: XTX_inv @ (XT @ y)
w = matrix_multiplication(XTX_inv, XTy)

# 5. Sum of elements
result_sum = np.sum(w)

print("w:\n", w)
print("Sum of elements of w:", result_sum)



w:
 [[0.01386421]
 [0.5049067 ]]
Sum of elements of w: 0.5187709081074008


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])