In [1]:
#introduction to numpy
import numpy as np

In [ ]:
#Creating arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10) #creates an array of size 10 of 1s

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,2.5) #fills the array with 2.5 of size 10

In [4]:
a = np.array([1,2,3,5,7,12])

In [ ]:
#multi dimension arrays

In [ ]:
np.zeros((5,2))

In [6]:
n = np.array([
    [1,2,3],
    [4,4,5]
])
n

array([[1, 2, 3],
       [4, 4, 5]])

In [ ]:
#randomly generated arrays

In [8]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [9]:
#element wise operations

a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [10]:
a + 1 #adds an element to each element or multiplies, divides whatever operation etc

array([1, 2, 3, 4, 5])

In [14]:
b = (10 + (a * 2)) ** 2 /100
b
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [15]:
#comparison operators a > 2
a > 2

a > b 

b > a 

array([ True,  True, False, False, False])

In [16]:
a[a > b]

array([2, 3, 4])